### ISSUE TITLE
timer synth ym5 support

### ISSUE THREAD

**Issue by combatopera** [combatopera/pym2149#10]
find a ym5 that actually uses it

**Comment by combatopera** [comment]
hard to find such a ym! but i can confirm ym5 digidrums work, so pwm effect probably works too, closing

**Comment by cyberic99** [comment]
For the record, what was the .ym you used?

**Comment by combatopera** [comment]
this mad max tune, i've had to zip it so it would attach [Lethal Xcess 1 - level 1.ym.zip](https://github.com/combatopera/pym2149/files/5953205/Lethal.Xcess.1.-.level.1.ym.zip)
