### ISSUE TITLE
digidrum support

### ISSUE THREAD

**Issue by cyberic99** [combatopera/pym2149#83]
Hello!

I just discovered your tools, and I would be interested in digidrum support.

I have a simple .ym with a digi in it. I can see the digi is logged, but I cannot hear it when using ym2wav.

do you plan to enable digis in the future?

Thank you

**Comment by combatopera** [comment]
Hi @cyberic99,
There wasn't a plan to implement digis. This ticket is now the plan. It shouldn't be too much work as a lot of the heavy lifting is already implemented for sid effect, but I'm not sure when I'll have time to do it. Can you attach your .ym file? And do you have an example of what you expect it to sound like?

**Comment by cyberic99** [comment]
Here is a zip file containing the .ym and a .wav export.

[simple_digi.zip](https://github.com/combatopera/pym2149/files/5867555/simple_digi.zip)

The .ym has been generated with Arkos Tracker, taking an example song and modifying it.

- StSound plays it correctly (the .wav has been generated with ym2wav fro StSound as well)
- AyEmul plays the file incorrectly, it seems to play too slow.
- And most other player fail to play it too

I can provide other examples if you need some, and I will be able to do some tests if you need it.

Thank you!

**Comment by combatopera** [comment]
thanks, that really helps

**Comment by cyberic99** [comment]
> thanks, that really helps

you're welcome, thank you for your interest in this feature !

**Comment by combatopera** [comment]
hi @cyberic99, please try version 27

**Comment by cyberic99** [comment]
yep it works great!

Thanks a lot for implementing digidrum support.

I tested ym2wav with a few songs, and some of them (not necessarily with digidrums) failed to convert (some have an unexpected header for instance)

Do you want me to open a separate issue?
I can do it, but maybe your are not that interested in supporting a wide range of ym formats/variants...

**Comment by combatopera** [comment]
yes, please open a new issue with the non-working ym files and i'll have a look. closing this one

**Comment by cyberic99** [comment]
I have opened a new issue here: https://github.com/combatopera/pym2149/issues/84
