### ISSUE TITLE
Missing support for non-interleaved YM files

### ISSUE THREAD

**Issue by retrocomputacion** [combatopera/pym2149#89]
Starting from YM4! version, the register dump can be in non-interleaved format, selected when bit0 of the DWord at file offset 16 is set to 0.

Files in this format seem to be rare, but pym2149 currently crashes when trying to load one of these files.

Some examples can be found in the clones1.zip file at http://www.genesis8bit.fr/frontend/music.php

**Comment by combatopera** [comment]
Thanks for the bug report, I will investigate this week hopefully. Do you have a link to relevant documentation? The info I've got on the YM format is patchy, and I may have left some areas unimplemented due to not being able to find test data at the time.

**Comment by retrocomputacion** [comment]
This file has the definition for each bit used in the Song attributes word:
[ftp://ftp.modland.com/pub/documents/format_documentation/Atari%20ST%20Sound%20Chip%20Emulator%20YM1-6%20(.ay,%20.ym).txt](url)

Im copying the relevant sections below:


```
YM4!

 Legend: BYTE            8 bits integer
         WORD           16 bits integer
         DWORD          32 bits integer
         String[n]      ASCCI string of n bytes length
         NT-String      NULL-terminated string


 WARNING: All DWORD or WORD are stored in MOTOROLA order in the file (INTEL reverse)

 ----------------------------------------------------------------
 Offset	Size	Type	    	Comment
 ----------------------------------------------------------------
 0	4	DWORD		ID of YM4 format. ('YM4!')
 4	8	String[8]	Check String ('LeOnArD!')
 12	4	DWORD		Nb of valid VBL of the file
 16	4	DWORD		Song attributes (see below)
 20	2	DWORD		Nb of digi-drum sample (can be 0)
 24	4	DWORD		Frame loop start (generally 0)



...




 Those who are reading till now have noticed that the YM3 format is an interleaved format.
 In fact, the YM4 format can be interleaved or not (Interleaved format offers a very powerfull
 compression ratio when compressed with LHA).


        Let's see the DWORD "song attribute":
        (bn represent the bit n of the DWORD)

        b0:     Set if Interleaved data block.
        b1:     Set if the digi-drum samples are signed data.
        b2:     Set if the digidrum is already in ST 4 bits format.

        b3-b31: Not used yet, MUST BE 0.
```

**Comment by combatopera** [comment]
looks like non-interleaved support broke when i migrated the project to python 3. fixed in version 30, which successfully starts playing all ym files in the above zip. @retrocomputacion can you confirm version 30 works for you?

**Comment by retrocomputacion** [comment]
Confirmed working now! Thanks!
